@startuml
abstract class BasicCylinderProperties {
    + Radius : float <<get>> <<set>>
}
class "Cylinder`1"<TCylinder> {
    + Cylinder(p1:Position, p2:Position, radius:float)
    + Property : TCylinder <<get>> <<set>>
    + Height : float <<get>>
    + Length : float <<get>>
    <<sealed>> + <<override>> SurfaceArea() : float
    <<sealed>> + <<override>> Volume() : float
    + BottomArea() : float
}
SShape <|-- "Cylinder`1"
@enduml
