@startuml
abstract class BasicTetrahedonProperty {
}
class "Tetrahedon`1"<TTetrahedon> {
    + Propriety : TTetrahedon <<get>> <<set>>
    + Tetrahedon(p1:Position, p2:Position, p3:Position, p4:Position)
    <<sealed>> + <<override>> SurfaceArea() : float
}
SShape <|-- "Tetrahedon`1"
@enduml
