@startuml
class Program {
}
class Node {
    + Node(d:int)
    + Data : int <<get>> <<set>>
    + Next : Node? <<get>> <<set>>
    + Prev : Node? <<get>> <<set>>
}
class DoubleLinkedList {
    + DoubleLinkedList()
    + Head : Node? <<get>> <<set>>
    + Tail : Node? <<get>> <<set>>
    + InsertFront(newData:int) : void
    + InsertLast(newData:int) : void
    + GetLastNode() : Node?
    + InsertAfter(key:int, newData:int) : void
    + FindbyKey(data:int) : Node?
    + deleteNodebyKey(key:int) : void
    + PrintList() : void
}
@enduml
